---
- name: Bootstrap SSH keys for EC2 instance
  hosts: web
  gather_facts: no
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/ubuntu/.ssh
        state: directory
        mode: '0700'
        owner: ubuntu
        group: ubuntu

    - name: Copy my id_ed25519.pub to authorized_keys
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
